### ISSUE TITLE
set-up the restaurant for opening

### ISSUE THREAD

**Issue by myka-p** [myka-p/CPNT-201-A1#1]
# Context

Prep needed to be done before opening the restaurant.

# Task list

- [ ] Turn on the lights
- [ ] Open the blinds
- [ ] Turn on TV & music
- [ ] Take out condiments for dine-in and place them in a bucket filled with ice
- [ ] Check menu availability with the kitchen
- [ ] Put ice in the ice bin
- [ ] Open umbrellas for patio

# Definition of done

If all the tasks from the task list have been done, the restaurant is ready to open.
