### ISSUE TITLE
repack and restock

### ISSUE THREAD

**Issue by myka-p** [myka-p/CPNT-201-A1#2]
# Context

Replenish the side dishes for to go orders by repacking them into small containers. Restock the beverage fridge as well.

# Task list

- [ ] check date dots/expiry dates for condiments
- [ ] repack pickled radish, corn salad, and coleslaw into 4oz container
- [ ] place date dots on side dishes, and organize them using FIFO (First In, First Out) if there are still old stocks
- [ ] store side dishes in the fridge
- [ ] check beverage fridge for drinks that are almost out
- [ ] restock drinks using FIFO method as well

# Definition of done

If all the tasks from the task list have been done.
