### ISSUE TITLE
keep the restaurant tidy

### ISSUE THREAD

**Issue by myka-p** [myka-p/CPNT-201-A1#3]
# Context

The following side duties are to be done mid-shift to keep restaurant tidy.

# Task list

- [ ] check washrooms
- [ ] wipe windows and door with glass cleaner
- [ ] wipe tablets
- [ ] store away glasses in the fridge when dry
- [ ] sweep if floor is dirty

# Definition of done

If all the tasks from the task list have been done.
