### ISSUE TITLE
clean up the restaurant

### ISSUE THREAD

**Issue by myka-p** [myka-p/CPNT-201-A1#4]
# Context

These tasks are to be done for closing.

# Task list

- [ ] Wipe the tables
- [ ] Sweep and mop the floor
- [ ] Turn off music and TV
- [ ] Clean washroom

# Definition of done

If all the tasks from the task list have been done.
