### ISSUE TITLE
close the till and cash-out

### ISSUE THREAD

**Issue by myka-p** [myka-p/CPNT-201-A1#5]
# Context

The following procedures are to be done to close the systems and view reports for the day's sales.

# Task list

- [ ] Close the debit/credit card machines.
- [ ] Print reports for sales.
- [ ] Calculate tip-out
- [ ] Count the cash drawer.
- [ ] Leave $200 dollars as float money.

# Definition of done

If all the tasks from the task list have been done, we can now close the restaurant and go home.
